[test]
coverage = true
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
coverageThreshold = { lines = 1.0, functions = 1.0, statements = 1.0 }
coveragePathIgnorePatterns = [
  "**/src/schema/**",
]
